//
// Copyright (c) 2018 Volterra, Inc. All rights reserved.
// Code generated by ves-gen-schema-go. DO NOT EDIT.
//
package vesenv

import (
	"context"
	"fmt"
	"strings"

	"github.com/gogo/protobuf/proto"

	"gopkg.volterra.us/stdlib/codec"
	"gopkg.volterra.us/stdlib/db"
	"gopkg.volterra.us/stdlib/errors"
)

var (
	// dummy imports in case file has no message with Refs
	_ db.Interface
	_ = errors.Wrap
	_ = strings.Split
)

// augmented methods on protoc/std generated struct

func (m *QuotaResourceKeyChoice) ToJSON() (string, error) {
	return codec.ToJSON(m)
}

func (m *QuotaResourceKeyChoice) ToYAML() (string, error) {
	return codec.ToYAML(m)
}

func (m *QuotaResourceKeyChoice) DeepCopy() *QuotaResourceKeyChoice {
	if m == nil {
		return nil
	}
	ser, err := m.Marshal()
	if err != nil {
		return nil
	}
	c := &QuotaResourceKeyChoice{}
	err = c.Unmarshal(ser)
	if err != nil {
		return nil
	}
	return c
}

func (m *QuotaResourceKeyChoice) DeepCopyProto() proto.Message {
	if m == nil {
		return nil
	}
	return m.DeepCopy()
}

func (m *QuotaResourceKeyChoice) Validate(ctx context.Context, opts ...db.ValidateOpt) error {
	return QuotaResourceKeyChoiceValidator().Validate(ctx, m, opts...)
}

type ValidateQuotaResourceKeyChoice struct {
	FldValidators map[string]db.ValidatorFunc
}

func (v *ValidateQuotaResourceKeyChoice) Validate(ctx context.Context, pm interface{}, opts ...db.ValidateOpt) error {
	m, ok := pm.(*QuotaResourceKeyChoice)
	if !ok {
		switch t := pm.(type) {
		case nil:
			return nil
		default:
			return fmt.Errorf("Expected type *QuotaResourceKeyChoice got type %s", t)
		}
	}
	if m == nil {
		return nil
	}

	switch m.GetChoice().(type) {
	case *QuotaResourceKeyChoice_VirtualHostPublic:
		if fv, exists := v.FldValidators["choice.virtual_host_public"]; exists {
			val := m.GetChoice().(*QuotaResourceKeyChoice_VirtualHostPublic).VirtualHostPublic
			vOpts := append(opts,
				db.WithValidateField("choice"),
				db.WithValidateField("virtual_host_public"),
			)
			if err := fv(ctx, val, vOpts...); err != nil {
				return err
			}
		}
	case *QuotaResourceKeyChoice_HealthcheckMinimumInterval:
		if fv, exists := v.FldValidators["choice.healthcheck_minimum_interval"]; exists {
			val := m.GetChoice().(*QuotaResourceKeyChoice_HealthcheckMinimumInterval).HealthcheckMinimumInterval
			vOpts := append(opts,
				db.WithValidateField("choice"),
				db.WithValidateField("healthcheck_minimum_interval"),
			)
			if err := fv(ctx, val, vOpts...); err != nil {
				return err
			}
		}

	}

	return nil
}

// Well-known symbol for default validator implementation
var DefaultQuotaResourceKeyChoiceValidator = func() *ValidateQuotaResourceKeyChoice {
	v := &ValidateQuotaResourceKeyChoice{FldValidators: map[string]db.ValidatorFunc{}}

	return v
}()

func QuotaResourceKeyChoiceValidator() db.Validator {
	return DefaultQuotaResourceKeyChoiceValidator
}
